on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: welfarecontainer1.azurecr.io
        username: ${{ secrets.acr_welfarecontainer1_username }}
        password: ${{ secrets.acr_welfarecontainer1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t welfarecontainer1.azurecr.io/welfareakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push welfarecontainer1.azurecr.io/welfareakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_welfareakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep welfare-aks-clusterb089 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace welfare-aks-clusterb089`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: welfare-aks-clusterb089
        container-registry-url: welfarecontainer1.azurecr.io
        container-registry-username: ${{ secrets.acr_welfarecontainer1_username }}
        container-registry-password: ${{ secrets.acr_welfarecontainer1_password }}
        secret-name: welfareakscldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: welfare-aks-clusterb089
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          welfarecontainer1.azurecr.io/welfareakscluster:${{ github.sha }}
        imagepullsecrets: |
          welfareakscldockerauth
